apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: ckad
subjects:
- kind: ServiceAccount
  name: my-sa
  namespace: ckad
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

