apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-http-echo.fullname" . }}
  labels:
    app: isw-http-echo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: isw-http-echo
