
kind: Service
apiVersion: v1
metadata:
  name: http-echo-service
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: 
    - LoadBalancer
  externalIPs: 
    - 172.17.17.126




