
# kind: Service
# apiVersion: v1
# metadata:
#   name: http-echo-service
# spec:
#   selector:
#     app: http-echo
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer



kind: Service
apiVersion: v1
metadata:
  name: http-echo-service
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30000
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
