
kind: Service
apiVersion: v1
metadata:
  name: http-echo-service
spec:
  clusterIP: None
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  # type: LoadBalancer

---
apiVersion: v1
kind: Endpoints
metadata:
  name: service
subsets:
  - addresses:
    - ip: 10.62.176.1
    ports:
      - port: 8080

