name: ci

on:
  push:
    branches:
      - "release/dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
          name: Debug secrets
          run: |
            echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
            echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"
#         name: Checkout
#         uses: actions/checkout@v4
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }} 
#           ecr: auto
#           logout: true
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       -
#         name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest


    