name: ci

on:
  push:
    branches:
      - "release/dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/img-http-echo:latest

      -
        name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      -
        name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      -
        name: Deploy 
      with:
        exec: helm upgrade APP_NAME ./helm-http-echo --install --wait --atomic --namespace=APP_NAMESPACE --values=./.helm-http-echo
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        # run: |
        #   helm upgrade --install http-echo-release ./helm-http-echo       
        # env:
        #   KUBECONFIG: ${{ secrets.KUBECONFIG }}
          